SELECT CUSTOMER_ID, MAX(PURCHASE_AMOUNT)
FROM ORDERS
GROUP BY CUSTOMER_ID;

SELECT SALESMAN_ID,ORDER_DATE,MAX(PURCHASE_AMOUNT)
FROM ORDERS
WHERE ORDER_DATE=To_DATE('2012/08/17', 'YYYY/MM/DD')
GROUP BY SALESMAN_ID,ORDER_DATE;

SELECT CUSTOMER_ID,ORDER_DATE,MAX(PURCHASE_AMOUNT)
FROM ORDERS
GROUP BY CUSTOMER_ID,ORDER_DATE
HAVING MAX(PURCHASE_AMOUNT)IN(2030, 3450, 5760, 6000);



