SELECT SUM(PURCHASE_AMOUNT) AS "TOTAL_PURCHASE_AMOUNT" FROM ORDERS;

SELECT AVG(PURCHASE_AMOUNT) AS "AVERAGE_PURCHASE_AMOUNT" FROM ORDERS;

SELECT MIN(PURCHASE_AMOUNT) AS "MINIMUM_PURCHASE_AMOUNT" FROM ORDERS;

SELECT MAX(PURCHASE_AMOUNT) AS "MAXIMUM_PURCHASE_AMOUNT" FROM ORDERS;

SELECT COUNT(DISTINCT SALESMAN_ID) AS TOTAL_SALESMAN FROM ORDERS;